version: '3.4'

services:
  foreningsportalen.api:
    image: ${DOCKER_REGISTRY-}foreningsportalenapi
    build:
      context: .
      dockerfile: ForeningsPortalen.Api/Dockerfile
    ports:
      - "8080:8080"

  foreningsportalen.website:
    image: ${DOCKER_REGISTRY-}foreningsportalenwebsite
    build:
      context: .
      dockerfile: ForeningsPortalen.Website/ForeningsPortalen.Website/Dockerfile
    environment:
        ForeningsPortalenBaseUrl: "http://foreningsportalen.api:8080"
    ports:
      - "8081:8080"
    depends_on:
        - foreningsportalen.api

