@_3.semesterProjekt.Api_HostAddress = http://localhost:5256
@Host=localhost
@Port=5256

@_3.semesterProjekt.Api_HostAddress = http://{{Host}}:{{Port}}

GET {{3.semesterProjekt.Api_HostAddress}}/api/User/3fa85f64-5717-4562-b3fc-2c963f66afa6

Accept: application/json



###

POST {{_3.semesterProjekt.Api_HostAddress}}/api/user
Content-Type: application/json

{
  //UserCreateRequestDto
}

###
